insert into country values(1, 'India')
insert into country values(2, 'Australia')
insert into state values(1, 'Telangana', 1)
insert into state values(2, 'Andhra Pradesh', 1)
insert into state values(3, 'Karnataka', 1)
insert into state values(4, 'Tamilnadu', 1)
insert into city values(1, 'Hyderabad', 1)
insert into city values(2, 'Warangal', 1)
insert into city values(3, 'Khammam', 1)
insert into city values(4, 'Vizag', 2)
insert into city values(5, 'Vijayawada', 2)
insert into city values(6, 'Bangalore', 3)
insert into city values(7, 'Chennai', 4)